### ISSUE TITLE
项目转换成功后启动报错  failed to load config from ******\vite.config.js

### ISSUE THREAD

**Issue by Jioho** [tnfe/wp2vite#22]
[wp2vite版本] ： wp2vite/2.0.1 win32-x64 node-v12.18.2
[项目demo]： ant-design Pro 版  https://github.com/vueComponent/ant-design-vue-pro.git
[报错信息]：
$ npm run dev

> vue-antd-pro@3.0.0 dev ******\ant-design-vue-pro
> vite

failed to load config from ******\ant-design-vue-pro\vite.config.js
error when starting dev server:
TypeError: (0 , import_vite_plugin_importer.usePluginImport) is not a function
    at vite_config_default (******\ant-design-vue-pro\vite.config.js:81:55)
    at loadConfigFromFile (******\ant-design-vue-pro\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:75511:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async resolveConfig (******\ant-design-vue-pro\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:75096:28)
    at async createServer (******\ant-design-vue-pro\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:73625:20)
    at async CAC.<anonymous> (******\ant-design-vue-pro\node_modules\vite\dist\node\cli.js:13963:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-antd-pro@3.0.0 dev: `vite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-antd-pro@3.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ******\AppData\Roaming\npm-cache\_logs\2021-08-11T06_22_05_914Z-debug.log

**Comment by wangzhengbo** [comment]
vue.config.js中的
import { usePluginImport } from 'vite-plugin-importer'; 
需要改成 
import usePluginImport from 'vite-plugin-importer';

**Comment by dravenww** [comment]
> vue.config.js中的
> import { usePluginImport } from 'vite-plugin-importer';
> 需要改成
> import usePluginImport from 'vite-plugin-importer';

对，后面修复下这个问题
